//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fields marked with (*) are mandatory.
        /// </summary>
        public static string FormHintMandatory {
            get {
                return ResourceManager.GetString("FormHintMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More details.
        /// </summary>
        public static string FormUserMore {
            get {
                return ResourceManager.GetString("FormUserMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dashboard.
        /// </summary>
        public static string MenuDashboardTitle {
            get {
                return ResourceManager.GetString("MenuDashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add New Client.
        /// </summary>
        public static string MenuPeopleClientCreate {
            get {
                return ResourceManager.GetString("MenuPeopleClientCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client List.
        /// </summary>
        public static string MenuPeopleClientsList {
            get {
                return ResourceManager.GetString("MenuPeopleClientsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à People.
        /// </summary>
        public static string MenuPeopleTitle {
            get {
                return ResourceManager.GetString("MenuPeopleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add New User.
        /// </summary>
        public static string MenuPeopleUserCreate {
            get {
                return ResourceManager.GetString("MenuPeopleUserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User List.
        /// </summary>
        public static string MenuPeopleUsersList {
            get {
                return ResourceManager.GetString("MenuPeopleUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projects List.
        /// </summary>
        public static string MenuProjectsList {
            get {
                return ResourceManager.GetString("MenuProjectsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projects.
        /// </summary>
        public static string MenuProjectsTitle {
            get {
                return ResourceManager.GetString("MenuProjectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resources.
        /// </summary>
        public static string MenuResourcesTitle {
            get {
                return ResourceManager.GetString("MenuResourcesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of Resources Types.
        /// </summary>
        public static string MenuResourcesTypeList {
            get {
                return ResourceManager.GetString("MenuResourcesTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome.
        /// </summary>
        public static string MessagesWelcome {
            get {
                return ResourceManager.GetString("MessagesWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string OptionsMenu {
            get {
                return ResourceManager.GetString("OptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add New Project.
        /// </summary>
        public static string ProjectManageCreateProject {
            get {
                return ResourceManager.GetString("ProjectManageCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List Of Projects.
        /// </summary>
        public static string ProjectManageProjectList {
            get {
                return ResourceManager.GetString("ProjectManageProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Project Management.
        /// </summary>
        public static string ProjectManageTitle {
            get {
                return ResourceManager.GetString("ProjectManageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go!.
        /// </summary>
        public static string SearchBouton {
            get {
                return ResourceManager.GetString("SearchBouton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please type an item to search....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activities.
        /// </summary>
        public static string UserManagementActivities {
            get {
                return ResourceManager.GetString("UserManagementActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add New User.
        /// </summary>
        public static string UserManagementCreateBTN {
            get {
                return ResourceManager.GetString("UserManagementCreateBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create New User.
        /// </summary>
        public static string UserManagementCreateMessage {
            get {
                return ResourceManager.GetString("UserManagementCreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users List.
        /// </summary>
        public static string UserManagementList {
            get {
                return ResourceManager.GetString("UserManagementList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profile.
        /// </summary>
        public static string UserManagementProfile {
            get {
                return ResourceManager.GetString("UserManagementProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Management.
        /// </summary>
        public static string UserManagementTitle {
            get {
                return ResourceManager.GetString("UserManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account Profile.
        /// </summary>
        public static string UserMenuProfile {
            get {
                return ResourceManager.GetString("UserMenuProfile", resourceCulture);
            }
        }
    }
}
